// Generated by i18next-cli — review and adapt to your project's needs.
// You may need to install dependencies: npm install i18next
//
// Other translation loading approaches:
//   • Static imports or bundled JSON: https://www.i18next.com/how-to/add-or-load-translations
//   • Lazy-load from a server: https://github.com/i18next/i18next-http-backend
//   • Manage translations with your team via Locize: https://www.locize.com
//     (see i18next-locize-backend: https://github.com/locize/i18next-locize-backend)
// import enTranslation from './locales/en/translation.json'
// import ruTranslation from './locales/ru/translation.json'

const enTranslation = {
  "navCashback": "get up to 25% cashback on first order",
  "navTrackOrder": "Track Order",

  "searchPlaceholder": "Search our product",
  "searchButton": "Search",
  "noResults": "No results",

  "profileLabel": "Profile",

  "cartLabel": "Shopping cart",
  "loading": "Loading...",
  "deleteItemLabel": "Delete item from cart",
  "increaseQuantityLabel": "Increase quantity",
  "decreaseQuantityLabel": "Decrease quantity",
  "cartTotal": "Cart Total",
  "orderNow": "Order Now",
  "alreadyInCart": "Already in cart",
  "addedToCart": "Added to cart",
  "alreadyAdded": "Already Added",
  "added": "Added",

  "shopCategories": "Shop Categories",

  "navHome": "HOME",
  "navCategories": "Categories",
  "navProducts": "Products",
  "navAbout": "About",

  "bannerTitle": "Smart Watches",
  "bannerSubtitle": "Amazing and Exclusive offers",
  "bannerPreviousLabel": "Previous slide",
  "bannerNextLabel": "Next slide",

  "categoriesTitle": "Categories",
  "categoriesPreviousLabel": "Previous categories",
  "categoriesNextLabel": "Next categories",

  "smartWatches": "Smart Watches",
  "mens-watches": "Men's Watches",
  "womens-watches": "Women's Watches",
  "furniture": "Furniture",
  "beauty": "Beauty",
  "mens-shoes": "Men's Shoes",
  "womens-shoes": "Women's Shoes",
  "groceries": "Groceries",
  "home-decoration": "Home Decoration",
  "kitchen-accessories": "Kitchen Accessories",
  "phones": "Phones",
  "sports-accessories": "Sports Accessories",
  "tablets": "Tablets",
  "womens-jewellery": "Women's Jewelery",
  "womens-dresses": "Women's Dresses",
  "womens-bags": "Women's Bags",
  "vehicle": "Vehicle",
  "tops": "Tops",
  "sunglasses": "Sunglasses",
  "mens-shirts": "Men's Shirts",
  "mobile-accessories": "Mobile Accessories",
  "motorcycle": "Motorcycle",
  "laptops": "Laptops",
  "watches": "Watches",
  "electronics": "Electronics",
  "smartphones": "Smartphones",
  "shoes": "Shoes",
  "fragrances": "Fragrances",
  "skin-care": "Skincare",
  "mensProducts": "Men's Products",
  "womensProducts": "Women's Products",
  "jewelry": "Jewelry",

  "productsTitle": "Products",

  "productImageLabel": "Product image",
  "paginationImageLabel": "Pagination image",
  "closePreviewLabel": "Close product preview",
  "previousImageLabel": "Previous image",
  "nextImageLabel": "Next image",
  "availability": "Availability",
  "addToCart": "Add to Cart",
  "selectImageLabel": "Select image",

  "footerDescription": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Distinctio excepturi iste temporibus cum perspiciatis placeat cupiditate ",
  "footerHome": "Home",
  "footerProducts": "Products",
  "footerCategories": "Categories",
  "footerSearch": "Search",
  "footerAbout": "About",
  "footerContact": "Contact us",
  "footerFollowUs": "Follow us",
  "footerLinkedinLabel": "LinkedIn profile",
  "footerGithubLabel": "GitHub profile",
  "footerEmailLabel": "Email us",

  "scrollTopLabel": "Scroll to top"
};

const ruTranslation = {
  "navCashback": "Кешбэк до 25% на первый заказ",
  "navTrackOrder": "Отследить заказ",

  "searchPlaceholder": "Поиск товаров",
  "searchButton": "Поиск",
  "noResults": "Нет результатов",

  "profileLabel": "Профиль",

  "cartLabel": "Корзина",
  "loading": "Загрузка...",
  "deleteItemLabel": "Удалить товар из корзины",
  "increaseQuantityLabel": "Увеличить количество",
  "decreaseQuantityLabel": "Уменьшить количество",
  "cartTotal": "Итог",
  "orderNow": "Заказать",
  "alreadyInCart": "Уже в корзине",
  "addedToCart": "Добавлено в корзину",
  "alreadyAdded": "Уже добавлено",
  "added": "Добавлено",

  "shopCategories": "Категории товаров",

  "navHome": "ГЛАВНАЯ",
  "navCategories": "Категории",
  "navProducts": "Товары",
  "navAbout": "О нас",

  "bannerTitle": "Умные часы",
  "bannerSubtitle": "Лучшие и эксклюзивные предложения",
  "bannerPreviousLabel": "Предыдущий слайд",
  "bannerNextLabel": "Следующий слайд",

  "categoriesTitle": "Категории",
  "categoriesPreviousLabel": "Предыдущие категории",
  "categoriesNextLabel": "Следующие категории",

  "smartWatches": "Умные часы",
  "furniture": "Мебель",
  "beauty": "Красота",
  "mens-watches": "Мужские часы",
  "womens-watches": "Женские часы",
  "mens-shoes": "Мужская обувь",
  "womens-shoes": "Женская обувь",
  "groceries": "Продукты",
  "home-decoration": "Домашний декор",
  "kitchen-accessories": "Кухонные принадлежности",
  "sports-accessories": "Спортивные принадлежности",
  "tablets": "Планшеты",
  "womens-jewellery": "Женские украшения",
  "womens-dresses": "Женские платья",
  "womens-bags": "Женские сумки",
  "vehicle": "Транспорт",
  "tops": "Топы",
  "sunglasses": "Солнцезащитные очки",
  "mens-shirts": "Мужские рубашки",
  "motorcycle": "Мотоциклы",
  "mobile-accessories": "Мобильные аксессуары",
  "phones": "Телефоны",
  "laptops": "Ноутбуки",
  "electronics": "Электроника",
  "smartphones": "Смартфоны",
  "watches": "Часы",
  "shoes": "Обувь",
  "fragrances": "Духи",
  "skin-care": "Уход за кожей",
  "mensProducts": "Товары для Мужчин",
  "womensProducts": "Товары для Женщин",
  "jewelry": "Ювелирные изделия",

  "productsTitle": "Товары",

  "productImageLabel": "Изображение товара",
  "paginationImageLabel": "Изображение навигации",
  "closePreviewLabel": "Закрыть предпросмотр товара",
  "previousImageLabel": "Предыдущее изображение",
  "nextImageLabel": "Следующее изображение",
  "availability": "Наличие",
  "addToCart": "Добавить в корзину",
  "selectImageLabel": "Выбрать изображение",

  "footerDescription": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Distinctio excepturi iste temporibus cum perspiciatis placeat cupiditate ",
  "footerHome": "Главная",
  "footerProducts": "Товары",
  "footerCategories": "Категории",
  "footerSearch": "Поиск",
  "footerAbout": "О нас",
  "footerContact": "Связаться с нами",
  "footerFollowUs": "Следите за нами",
  "footerLinkedinLabel": "Профиль LinkedIn",
  "footerGithubLabel": "Профиль GitHub",
  "footerEmailLabel": "Напишите нам",

  "scrollTopLabel": "Прокрутить вверх"
};


i18next.init({
    returnEmptyString: false,
    fallbackLng: 'en',
    lng: localStorage.getItem('lang') || 'en',
    defaultNS: 'translation',
    resources: {
      en: { translation: enTranslation },
      ru: { translation: ruTranslation },
    },
});


export function updateContent() {
  document.querySelectorAll("[data-i18n]").forEach(el => {
    el.textContent = i18next.t(el.dataset.i18n);
  });

  document.querySelectorAll("[data-i18n-placeholder]").forEach(el => {
    el.placeholder = i18next.t(el.dataset.i18nPlaceholder);
  });

  document.querySelectorAll("[data-i18n-aria]").forEach(el => {
    el.setAttribute("aria-label", i18next.t(el.dataset.i18nAria));
  });
}

export default i18next;
